apiVersion: v1
kind: Service
metadata:
  name: WebApplication1
  labels:
     app: WebApplication1
spec:
  ports:
  -port: 80
  targetPort: 80
  selector:
    app: WebApplication1
  type: LoadBalancer