apiVersion: v1
kind: Service
metadata:
  name: webapplication1
spec:
  type: LoadBalancer
  selector:
    app: webapplication1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
