apiVersion: apps/v1
kind: Deployment
metadata:
  name: WebApplication1
  labels:
    app: WebApplication1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: WebApplication1
  template:
    metadata:
      labels:
        app: WebApplication1
    spec:
      containers:
      - name: webapplication1
        image: 868287237824.dkr.ecr.us-east-1.amazonaws.com/webapplication1:webapplication1
        ports:
        - containerPort: 80
